# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e40a64e635199e1d350aac2a55888a97f742fbd87a5a3f2dce44afe41fe0ea5d8b82375229f0a91adc6ed14fac156c7065a4b04adf2ea16a2a72d21727394bee

test:
  secret_key_base: 4c18b943add27e29cbd194b9f778823ea37c82218b38260e0b33130baf7cc9a41fda18b2819bfd85ea89865efc46437de6761bfac3e676becd58aab4c518debd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
